/** Dados do portfólio reutilizados (Contact, Chatbot, etc.) */
export const SITE_PROFILE = {
  fullName: 'Matheus Pereira de Souza',
  shortName: 'Matheus Pereira',
  email: 'matheuspereira6464@gmail.com',
  /** Apenas dígitos com código do país (55…) — usado em tel: e nas respostas do chat */
  phoneDigits: '5592992138870',
  phoneDisplayPt: '+55 (92) 99213-8870',
  phoneDisplayEn: '+55 (92) 99213-8870',
  /** valor para href tel: */
  phoneTel: '+5592992138870',
  linkedin: 'https://www.linkedin.com/in/matheus-pereira64/',
  linkedinActivity: 'https://www.linkedin.com/in/matheus-pereira64/recent-activity/all/',
  github: 'https://github.com/MatheusPereira64',
  portfolioUrl: 'https://matheuspereira64.github.io/Portfolio/',
  /**
   * Domínio no Plausible (ex.: matheuspereira64.github.io).
   * Crie a conta em https://plausible.io e confirme o domínio.
   * Pode sobrescrever com VITE_PLAUSIBLE_DOMAIN.
   */
  plausibleDomain: 'matheuspereira64.github.io',
}

export const CV_FILES = {
  en: 'CV - Matheus Pereira - 2026 - English.pdf',
  pt: 'CV PT-BR - Matheus Pereira - 2026 .pdf',
}

/** PDFs live only in `public/curriculo/`. `docs/curriculo/` is generated by `npm run build`. */

/** @deprecated prefer getCvFilename('en') */
export const CV_FILENAME = CV_FILES.en

export function getCvFilename(locale = 'en') {
  return CV_FILES[locale === 'pt' ? 'pt' : 'en']
}

export function getCvHref(locale = 'en') {
  return `${import.meta.env.BASE_URL}curriculo/${encodeURIComponent(getCvFilename(locale))}`
}

export function triggerCvDownload(locale = 'en') {
  const filename = getCvFilename(locale)
  const url = getCvHref(locale)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.rel = 'noopener noreferrer'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

/** Foto de perfil profissional (public/images/) */
export const PROFILE_IMAGE = 'images/matheus-profile.png'

export function profileImageUrl() {
  return `${import.meta.env.BASE_URL}${PROFILE_IMAGE}`
}
